name: Github Actions - Release

# Run on every commit tag (e.g. 1.0.1)
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish new library version

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Message
        run: echo "Hello user, I am triggered because of tag ${{github.ref_name}} push on branch $GITHUB_REF ${{github.ref}}"
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch
        run: |
          branch_raw=$(git branch -r)
          branch=${branch_raw/origin\/}
          branch_test=test
          echo "BRANCH_RAW=$(echo ${branch_raw})" >> $GITHUB_ENV
          echo "BRANCH_TEST=$(echo ${branch_test})" >> $GITHUB_ENV

      - name: Get Branch
        run: echo $BRANCH

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Run deploy
        run: npm publish
