name: Github Actions - Release

# Run on every commit tag (e.g. 1.0.1)
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish new library version

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}
      - name: Message
        run: echo "Hello user, I am triggered because of tag ${{github.ref_name}} push on branch $GITHUB_REF ${{github.ref}}"
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Run deploy
        run: npm publish
