name: Github Actions - Release

# Run on every commit tag (e.g. 1.0.1)
on:
  push:
    tags:
      - '*'

jobs:
  branch_set:
    name: Set current branch name
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set branch name in env file
        run: |
          branch_raw=$(git branch -r --contains ${{ github.ref }})
          branch=${branch_raw##*/}
          echo "BRANCH=$(echo ${branch})" >> $GITHUB_ENV

      - name: Get Branch
        run: echo $BRANCH

  release:
    name: Publish new library version
    needs: branch_set
    if: $BRANCH == 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Message
        run: echo "I am triggered because of tag ${{github.ref_name}} push on branch $BRANCH"
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Run deploy
        run: npm publish
